apiVersion: apps/v1
kind: Deployment
metadata:
  name: calorie-app-deployment
  labels:
    app: calorie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calorie-app
  template:
    metadata:
      labels:
        app: calorie-app
    spec:
      containers:
        - name: calorie-app
          image: azurewinterproject.azurecr.io/calories_service_image
          ports:
            - containerPort: 50