apiVersion: apps/v1
kind: Deployment
metadata:
  name: calorie-app-deployment
  labels:
    app: calorie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calorie-app
  template:
    metadata:
      labels:
        app: calorie-app
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
        - name: calorie-app
          image: azurewinterproject.azurecr.io/calories_service_image
          volumeMounts:
            - name: secrets-store01-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          ports:
            - containerPort: 50
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-system-msi"
