apiVersion: v1
kind: Service
metadata:
  name: calorie-app-cluster-ip-service
  namespace: prod
  labels:
    app: calorie-app
spec:
  type: ClusterIP
  selector:
    app: calorie-app
  ports:
    - port: 50
      targetPort: 50

