apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app-deployment
  labels:
    app: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: azurewinterproject.azurecr.io/kshitijkumarakswinterprojectbackend
          ports:
            - containerPort: 90