apiVersion: v1
kind: Service
metadata:
  name: user-app-cluster-ip-service
  namespace: prod
  labels:
    app: user-app
spec:
  type: ClusterIP
  selector:
    app: user-app
  ports:
    - port: 90
      targetPort: 90

