apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app-deployment
  labels:
    app: fitness-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness-app
  template:
    metadata:
      labels:
        app: fitness-app
    spec:
      containers:
        - name: fitness-app
          image: azurewinterproject.azurecr.io/fitness_service_image
          ports:
            - containerPort: 60