apiVersion: v1
kind: Service
metadata:
  name: fitness-app-cluster-ip-service
  namespace: prod
  labels:
    app: fitness-app
spec:
  type: ClusterIP
  selector:
    app: fitness-app
  ports:
    - port: 60
      targetPort: 60

